export const Exp = [
  {
    id: 1,
    title: 'Backend Developer',
    employer: 'Capitual',
    date: '10/2021 - 08/2022',
    acts: [
      { id: 1, act: 'Backend Development' },
      { id: 2, act: 'Tests Development' },
      { id: 3, act: 'Application Monitoring' },
      { id: 4, act: 'Features Development' },
      { id: 5, act: 'Map Technologies and Document' },
      { id: 6, act: ' Tech Crisis Containment' },
    ],
  },
  {
    id: 2,
    title: 'FullStack Developer',
    employer: 'Dev2Grow',
    date: '03/2021 - 06/2021',
    acts: [
        { id: 1, act: 'Backend Development' },
        { id: 2, act: 'Tests Development' },
        { id: 3, act: 'Application Monitoring' },
        { id: 4, act: 'Features Development' },
        { id: 5, act: 'Map Technologies and Document' },
        { id: 6, act: ' Tech Crisis Containment' },
      ],
  },
  {
    id: 3,
    title: 'FullStack Developer',
    employer: 'Dev2Grow',
    date: '03/2021 - 06/2021',
    acts: [
        { id: 1, act: 'Backend Development' },
        { id: 2, act: 'Tests Development' },
        { id: 3, act: 'Application Monitoring' },
        { id: 4, act: 'Features Development' },
        { id: 5, act: 'Map Technologies and Document' },
        { id: 6, act: ' Tech Crisis Containment' },
      ],
  },
  {
    id: 4,
    title: 'FullStack Developer',
    employer: 'Dev2Grow',
    date: '03/2021 - 06/2021',
    acts: [
        { id: 1, act: 'Backend Development' },
        { id: 2, act: 'Tests Development' },
        { id: 3, act: 'Application Monitoring' },
        { id: 4, act: 'Features Development' },
        { id: 5, act: 'Map Technologies and Document' },
        { id: 6, act: ' Tech Crisis Containment' },
      ],
  },
];
