export const Skill = [
  {
    id: 1,
    name: 'HTML5',
    icon: 'html5',
    font: 'fontawesome',
  },
  {
    id: 2,
    name: 'CSS3',
    icon: 'css3',
    font: 'fontawesome',
  },
  {
    id: 3,
    name: 'JavaScript',
    icon: 'js',
    font: 'fontawesome',
  },
  {
    id: 4,
    name: 'NodeJs',
    icon: 'node',
    font: 'fontawesome',
  },
  {
    id: 5,
    name: 'Typescript',
    icon: 'language-typescript',
    font: 'materialcomunity',
  },
  {
    id: 6,
    name: 'Golang',
    icon: 'google',
    font: 'fontawesome',
  },
  {
    id: 7,
    name: 'ReactJs',
    icon: 'react',
    font: 'fontawesome',
  },
  {
    id: 8,
    name: 'Git',
    icon: 'git',
    font: 'fontawesome',
  },
  {
    id: 9,
    name: 'PostgreSQL',
    icon: 'database',
    font: 'fontawesome',
  },
  {
    id: 10,
    name: 'MongoDb',
    icon: 'mongodb',
    font: 'fontisto',
  },
  {
    id: 13,
    name: 'Docker',
    icon: 'docker',
    font: 'fontawesome',
  },
  {
    id: 14,
    name: 'Amazon Web Services',
    icon: 'aws',
    font: 'fontawesome',
  },
  {
    id: 15,
    name: 'Angular',
    icon: 'angular',
    font: 'fontawesome',
  },
];
